# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Registeration_Screen.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Register(object):
    def setupUi(self, Dialog_Register):
        Dialog_Register.setObjectName("Dialog_Register")
        Dialog_Register.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/newUser_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog_Register.setWindowIcon(icon)
        Dialog_Register.setModal(True)
        self.groupBox = QtWidgets.QGroupBox(Dialog_Register)
        self.groupBox.setGeometry(QtCore.QRect(80, 50, 491, 321))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 7, 1)
        self.label_firstName = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_firstName.setFont(font)
        self.label_firstName.setObjectName("label_firstName")
        self.gridLayout_2.addWidget(self.label_firstName, 3, 0, 1, 1)
        self.label_userCity = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_userCity.setFont(font)
        self.label_userCity.setObjectName("label_userCity")
        self.gridLayout_2.addWidget(self.label_userCity, 5, 0, 1, 1)
        self.label_rPass = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_rPass.setFont(font)
        self.label_rPass.setObjectName("label_rPass")
        self.gridLayout_2.addWidget(self.label_rPass, 1, 0, 1, 1)
        self.label_lastName = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_lastName.setFont(font)
        self.label_lastName.setObjectName("label_lastName")
        self.gridLayout_2.addWidget(self.label_lastName, 4, 0, 1, 1)
        self.label_rUser = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_rUser.setFont(font)
        self.label_rUser.setObjectName("label_rUser")
        self.gridLayout_2.addWidget(self.label_rUser, 0, 0, 1, 1)
        self.label_userType = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_userType.setFont(font)
        self.label_userType.setObjectName("label_userType")
        self.gridLayout_2.addWidget(self.label_userType, 6, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_rcancel = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_rcancel.setFont(font)
        self.pushButton_rcancel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_rcancel.setObjectName("pushButton_rcancel")
        self.horizontalLayout_2.addWidget(self.pushButton_rcancel)
        self.pushButton_add = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_2.addWidget(self.pushButton_add)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.label_newUser_background = QtWidgets.QLabel(Dialog_Register)
        self.label_newUser_background.setGeometry(QtCore.QRect(-200, -48, 971, 571))
        self.label_newUser_background.setStyleSheet("image:url(:/newPrefix/background.jpg)")
        self.label_newUser_background.setText("")
        self.label_newUser_background.setObjectName("label_newUser_background")
        self.label_newUser_background.raise_()
        self.groupBox.raise_()

        self.retranslateUi(Dialog_Register)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Register)

    def retranslateUi(self, Dialog_Register):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Register.setWindowTitle(_translate("Dialog_Register", "Registration"))
        self.groupBox.setTitle(_translate("Dialog_Register", "Register as New User"))
        self.label.setText(_translate("Dialog_Register", " Confirm Password "))
        self.checkBox.setText(_translate("Dialog_Register", " Agent "))
        self.checkBox_2.setText(_translate("Dialog_Register", " Officer"))
        self.label_firstName.setText(_translate("Dialog_Register", " First Name "))
        self.label_userCity.setText(_translate("Dialog_Register", " City"))
        self.label_rPass.setText(_translate("Dialog_Register", " Password"))
        self.label_lastName.setText(_translate("Dialog_Register", " Last Name"))
        self.label_rUser.setText(_translate("Dialog_Register", " Username "))
        self.label_userType.setText(_translate("Dialog_Register", " Type"))
        self.pushButton_rcancel.setText(_translate("Dialog_Register", "Cancel"))
        self.pushButton_add.setText(_translate("Dialog_Register", "Add"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Register = QtWidgets.QDialog()
    ui = Ui_Dialog_Register()
    ui.setupUi(Dialog_Register)
    Dialog_Register.show()
    sys.exit(app.exec_())
