from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_oMenu(object):
    def setupUi(self, Dialog_oMenu):
        Dialog_oMenu.setObjectName("Dialog_oMenu")
        Dialog_oMenu.resize(640, 480)
        Dialog_oMenu.setMinimumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Resource/menu_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dialog_oMenu.setWindowIcon(icon)
        Dialog_oMenu.setStyleSheet("background-color: rgb(255, 255, 255);")
        Dialog_oMenu.setModal(True)
        self.tabWidget = QtWidgets.QTabWidget(Dialog_oMenu)
        self.tabWidget.setGeometry(QtCore.QRect(-4, -1, 651, 481))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        #Added 3 line of code to disable Close and Help button 
        self.setWindowFlags(self.windowFlags() | QtCore.Qt.CustomizeWindowHint)
        self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowCloseButtonHint)       
        self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowContextHelpButtonHint)        
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_ticket = QtWidgets.QWidget()
        self.tab_ticket.setObjectName("tab_ticket")
        self.groupBox_reg = QtWidgets.QGroupBox(self.tab_ticket)
        self.groupBox_reg.setGeometry(QtCore.QRect(10, 30, 611, 181))
        self.groupBox_reg.setTitle("")
        self.groupBox_reg.setObjectName("groupBox_reg")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_reg)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 371, 128))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_name.setReadOnly(True)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.lineEdit_make = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_make.setReadOnly(True)
        self.lineEdit_make.setObjectName("lineEdit_make")
        self.verticalLayout.addWidget(self.lineEdit_make)
        self.lineEdit_model = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_model.setReadOnly(True)
        self.lineEdit_model.setObjectName("lineEdit_model")
        self.verticalLayout.addWidget(self.lineEdit_model)
        self.lineEdit_colour = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_colour.setReadOnly(True)
        self.lineEdit_colour.setObjectName("lineEdit_colour")
        self.verticalLayout.addWidget(self.lineEdit_colour)
        self.lineEdit_year = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_year.setReadOnly(True)
        self.lineEdit_year.setObjectName("lineEdit_year")
        self.verticalLayout.addWidget(self.lineEdit_year)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 5, 1)
        self.label_make = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_make.setFont(font)
        self.label_make.setObjectName("label_make")
        self.gridLayout.addWidget(self.label_make, 1, 0, 1, 1)
        self.label_model = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_model.setFont(font)
        self.label_model.setObjectName("label_model")
        self.gridLayout.addWidget(self.label_model, 2, 0, 1, 1)
        self.label_colour = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_colour.setFont(font)
        self.label_colour.setObjectName("label_colour")
        self.gridLayout.addWidget(self.label_colour, 3, 0, 1, 1)
        self.label_year = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_year.setFont(font)
        self.label_year.setObjectName("label_year")
        self.gridLayout.addWidget(self.label_year, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_reg)
        self.label.setGeometry(QtCore.QRect(430, 60, 161, 101))
        self.label.setStyleSheet("image: url(:/Resource/car_icon.png)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.groupBox_reg)
        self.widget.setGeometry(QtCore.QRect(13, 10, 591, 26))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_check = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_check.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Resource/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_check.setIcon(icon1)
        self.pushButton_check.setObjectName("pushButton_check")
        self.pushButton_check.setDefault(True)        
        self.gridLayout_4.addWidget(self.pushButton_check, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_registration = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_registration.setFont(font)
        self.label_registration.setObjectName("label_registration")
        self.horizontalLayout.addWidget(self.label_registration)
        self.lineEdit_registration = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_registration.setText("")
        self.lineEdit_registration.setObjectName("lineEdit_registration")
        self.horizontalLayout.addWidget(self.lineEdit_registration)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.label_background = QtWidgets.QLabel(self.tab_ticket)
        self.label_background.setGeometry(QtCore.QRect(-34, -128, 841, 661))
        self.label_background.setStyleSheet("image: url(:/Resource/background.jpg)")
        self.label_background.setText("")
        self.label_background.setObjectName("label_background")
        self.groupBox_ticket = QtWidgets.QGroupBox(self.tab_ticket)
        self.groupBox_ticket.setGeometry(QtCore.QRect(130, 229, 381, 171))
        self.groupBox_ticket.setTitle("")
        self.groupBox_ticket.setFlat(False)
        self.groupBox_ticket.setCheckable(False)
        self.groupBox_ticket.setObjectName("groupBox_ticket")
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_ticket)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 321, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_vDate = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_vDate.setFont(font)
        self.label_vDate.setObjectName("label_vDate")
        self.gridLayout_3.addWidget(self.label_vDate, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_vDate = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_vDate.setObjectName("lineEdit_vDate")
        self.gridLayout_2.addWidget(self.lineEdit_vDate, 0, 0, 1, 1)
        self.lineEdit_violation = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_violation.setObjectName("lineEdit_violation")
        self.gridLayout_2.addWidget(self.lineEdit_violation, 1, 0, 1, 1)
        self.lineEdit_fine = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_fine.setObjectName("lineEdit_fine")
        self.gridLayout_2.addWidget(self.lineEdit_fine, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 3, 1)
        self.label_violation = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_violation.setFont(font)
        self.label_violation.setObjectName("label_violation")
        self.gridLayout_3.addWidget(self.label_violation, 1, 0, 1, 1)
        self.label_fine = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fine.setFont(font)
        self.label_fine.setObjectName("label_fine")
        self.gridLayout_3.addWidget(self.label_fine, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_ticNum = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_ticNum.setFont(font)
        self.label_ticNum.setObjectName("label_ticNum")
        self.horizontalLayout_2.addWidget(self.label_ticNum)
        self.lineEdit_ticNum = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_ticNum.setReadOnly(True)
        self.lineEdit_ticNum.setObjectName("lineEdit_ticNum")
        self.horizontalLayout_2.addWidget(self.lineEdit_ticNum)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pushButton_cancel = QtWidgets.QPushButton(self.tab_ticket)
        self.pushButton_cancel.setGeometry(QtCore.QRect(550, 3, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Resource/x_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_cancel.setIcon(icon2)
        self.pushButton_cancel.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_issue = QtWidgets.QPushButton(self.tab_ticket)
        self.pushButton_issue.setGeometry(QtCore.QRect(550, 410, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_issue.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Resource/ticButton_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_issue.setIcon(icon3)
        self.pushButton_issue.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_issue.setObjectName("pushButton_issue")
        self.pushButton_issue.setDefault(False)        
        self.label_background.raise_()
        self.groupBox_reg.raise_()
        self.groupBox_ticket.raise_()
        self.pushButton_cancel.raise_()
        self.pushButton_issue.raise_()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Resource/ticket_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_ticket, icon4, "")
        self.tab_car = QtWidgets.QWidget()
        self.tab_car.setObjectName("tab_car")
        self.label_background_2 = QtWidgets.QLabel(self.tab_car)
        self.label_background_2.setGeometry(QtCore.QRect(-120, -80, 841, 661))
        self.label_background_2.setStyleSheet("image: url(:/Resource/background.jpg)")
        self.label_background_2.setText("")
        self.label_background_2.setObjectName("label_background_2")
        self.groupBox_search = QtWidgets.QGroupBox(self.tab_car)
        self.groupBox_search.setGeometry(QtCore.QRect(29, 19, 581, 89))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_search.setFont(font)
        self.groupBox_search.setObjectName("groupBox_search")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_search)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_left = QtWidgets.QGridLayout()
        self.gridLayout_left.setObjectName("gridLayout_left")
        self.label_make_2 = QtWidgets.QLabel(self.groupBox_search)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_make_2.setFont(font)
        self.label_make_2.setObjectName("label_make_2")
        self.gridLayout_left.addWidget(self.label_make_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_make_2 = QtWidgets.QLineEdit(self.groupBox_search)
        self.lineEdit_make_2.setObjectName("lineEdit_make_2")
        self.verticalLayout_3.addWidget(self.lineEdit_make_2)
        self.gridLayout_left.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.label_year_2 = QtWidgets.QLabel(self.groupBox_search)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_year_2.setFont(font)
        self.label_year_2.setObjectName("label_year_2")
        self.gridLayout_left.addWidget(self.label_year_2, 1, 0, 1, 1)
        self.lineEdit_year_2 = QtWidgets.QLineEdit(self.groupBox_search)
        self.lineEdit_year_2.setObjectName("lineEdit_year_2")
        self.gridLayout_left.addWidget(self.lineEdit_year_2, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_left)
        self.gridLayout_right = QtWidgets.QGridLayout()
        self.gridLayout_right.setObjectName("gridLayout_right")
        self.label_colour_2 = QtWidgets.QLabel(self.groupBox_search)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_colour_2.setFont(font)
        self.label_colour_2.setObjectName("label_colour_2")
        self.gridLayout_right.addWidget(self.label_colour_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_model_2 = QtWidgets.QLineEdit(self.groupBox_search)
        self.lineEdit_model_2.setObjectName("lineEdit_model_2")
        self.verticalLayout_4.addWidget(self.lineEdit_model_2)
        self.gridLayout_right.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.label_model_2 = QtWidgets.QLabel(self.groupBox_search)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_model_2.setFont(font)
        self.label_model_2.setObjectName("label_model_2")
        self.gridLayout_right.addWidget(self.label_model_2, 0, 0, 1, 1)
        self.lineEdit_colour_2 = QtWidgets.QLineEdit(self.groupBox_search)
        self.lineEdit_colour_2.setObjectName("lineEdit_colour_2")
        self.gridLayout_right.addWidget(self.lineEdit_colour_2, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_right)
        self.groupBox = QtWidgets.QGroupBox(self.tab_car)
        self.groupBox.setGeometry(QtCore.QRect(30, 140, 581, 291))
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 20, 541, 251))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_list = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_list.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_list.setObjectName("gridLayout_list")
        self.verticalLayout_ONE = QtWidgets.QVBoxLayout()
        self.verticalLayout_ONE.setObjectName("verticalLayout_ONE")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_1.setReadOnly(True)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.verticalLayout_ONE.addWidget(self.lineEdit_1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_ONE.addWidget(self.lineEdit_2)
        self.gridLayout_list.addLayout(self.verticalLayout_ONE, 0, 0, 1, 1)
        self.verticalLayout_TWO = QtWidgets.QVBoxLayout()
        self.verticalLayout_TWO.setObjectName("verticalLayout_TWO")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_TWO.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_TWO.addWidget(self.lineEdit_4)
        self.gridLayout_list.addLayout(self.verticalLayout_TWO, 1, 0, 1, 1)
        self.verticalLayout_THREE = QtWidgets.QVBoxLayout()
        self.verticalLayout_THREE.setObjectName("verticalLayout_THREE")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_THREE.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_THREE.addWidget(self.lineEdit_6)
        self.gridLayout_list.addLayout(self.verticalLayout_THREE, 2, 0, 1, 1)
        self.verticalLayout_FOUR = QtWidgets.QVBoxLayout()
        self.verticalLayout_FOUR.setObjectName("verticalLayout_FOUR")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_FOUR.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_FOUR.addWidget(self.lineEdit_8)
        self.gridLayout_list.addLayout(self.verticalLayout_FOUR, 3, 0, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_car)
        self.layoutWidget3.setGeometry(QtCore.QRect(440, 110, 158, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_find = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_find.setFont(font)
        self.pushButton_find.setIcon(icon1)
        self.pushButton_find.setObjectName("pushButton_find")
        self.horizontalLayout_5.addWidget(self.pushButton_find)
        self.pushButton_cancel_2 = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Lato")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cancel_2.setFont(font)
        self.pushButton_cancel_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_cancel_2.setIcon(icon2)
        self.pushButton_cancel_2.setIconSize(QtCore.QSize(12, 12))
        self.pushButton_cancel_2.setObjectName("pushButton_cancel_2")
        self.horizontalLayout_5.addWidget(self.pushButton_cancel_2)
        self.tabWidget.addTab(self.tab_car, icon1, "")

        self.retranslateUi(Dialog_oMenu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog_oMenu)

    def retranslateUi(self, Dialog_oMenu):
        _translate = QtCore.QCoreApplication.translate
        Dialog_oMenu.setWindowTitle(_translate("Dialog_oMenu", "Menu"))
        self.label_name.setText(_translate("Dialog_oMenu", " Name"))
        self.label_make.setText(_translate("Dialog_oMenu", " Make"))
        self.label_model.setText(_translate("Dialog_oMenu", " Model"))
        self.label_colour.setText(_translate("Dialog_oMenu", " Colour"))
        self.label_year.setText(_translate("Dialog_oMenu", "  Year"))
        self.pushButton_check.setText(_translate("Dialog_oMenu", "Check"))
        self.label_registration.setText(_translate("Dialog_oMenu", " Registration Number "))
        self.label_vDate.setText(_translate("Dialog_oMenu", " Violation Date "))
        self.label_violation.setText(_translate("Dialog_oMenu", " Violation "))
        self.label_fine.setText(_translate("Dialog_oMenu", " Fine Amount "))
        self.label_ticNum.setText(_translate("Dialog_oMenu", " Ticket Number "))
        self.pushButton_cancel.setText(_translate("Dialog_oMenu", " Cancel"))
        self.pushButton_issue.setText(_translate("Dialog_oMenu", " Issue"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ticket), _translate("Dialog_oMenu", "Issue Ticket"))
        self.groupBox_search.setTitle(_translate("Dialog_oMenu", "Search"))
        self.label_make_2.setText(_translate("Dialog_oMenu", " Make"))
        self.label_year_2.setText(_translate("Dialog_oMenu", " Year"))
        self.label_colour_2.setText(_translate("Dialog_oMenu", " Colour"))
        self.label_model_2.setText(_translate("Dialog_oMenu", " Model"))
        self.groupBox.setTitle(_translate("Dialog_oMenu", "Results"))
        self.pushButton_find.setText(_translate("Dialog_oMenu", "Find"))
        self.pushButton_cancel_2.setText(_translate("Dialog_oMenu", " Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_car), _translate("Dialog_oMenu", "Search for Car Owner"))
import source_rc